### ISSUE TITLE
Possible Issue/Maybe Just a Question: Resuming Streamed Episodes

### ISSUE THREAD

**Issue by driverkt** [trevorsharp/youtubecast#16] opened 2024-04-02 16:08 UTC
Recently (I don't think this has always been the case), when I am watching a video via my podcast app (I use Apple Podcasts), I have noticed an issue. I'll attempt to describe it below. 

Say that I am watching a longer "video"/podcast episode and I choose to pause it and come back later. I have noticed that I can't reliably resume an episode. For example, consider the below video from Veritasium: 

![Why is this number everywhere jpeg](https://github.com/trevorsharp/youtubecast/assets/1783591/17d81792-35f5-47c9-82e3-fa37acd6bce1)

Note that I have my settings such that episodes aren't automatically downloaded -- I just stream them. 

If I download the episode, I have no trouble continuing from the point where I left off. 

Is this a characteristic of youtubecast, such that there is something about resuming a stream of a video that isn't quite hooked up with the correct parameters in the url? For example, I know I can edit the URL of a YouTube video by appending an `&t=1m35s` and start from that point in the video. 

Curious about your thoughts. I haven't looked into the code yet, but maybe I will if I get some time. 

Thanks for an amazing service! Truly valuable!

**Comment by trevorsharp** [comment] 2024-04-06 04:50
I’ve tested this out on Apple Podcasts and was able to reproduce the behavior. Unfortunately, it seems to be an issue on the client app side and not on the YouTubeCast side. 

My best guess is that the client is trying to cache some of the streamed video and if you try to resume playback after closing the app, it tries to pick up from the cached version, which may be incomplete or corrupted. I can tell from testing that when this error pops up, the podcast app isn’t even making a call to the server to try and load the video. 

There were two ways I found that work to get the video playing again — the first was deleting the Apple Podcasts app and re-downloading (this was suggested on a [support thread](https://discussions.apple.com/thread/254727701) for a similar issue and my guess is this clears away any broken cache) and the second way to get the episode to play was downloading the broken episode in the podcast app and then playing it (this forces the app to do a full download of the file).

There doesn’t seem to be anything that could reasonably be done to avoid this behavior on the YouTubeCast side. I’ve personally been using Pocket Casts due to other issues I’ve had in the past with Apple Podcasts, and I haven’t experienced any issues with playback.

**Closed as not planned by trevorsharp** 2024-04-06 04:50 UTC
